// src/projects/vueApp/src/App.vue
<script setup lang="ts">
import { ref, watch } from "vue";
import { jumpProject } from "@/utils";
import HelloWorld from "./components/HelloWorld.vue";
const whiteList: string[] = ["http://localhost:8080"];
window.addEventListener(
  "message",
  (event) => {
    if (!whiteList.includes(event.origin)) return;
    localStorage.setItem("count", event.data);
  },
  false
);
let initCount = ref(Number(localStorage.getItem("count")));
watch(initCount, (newVal) => localStorage.setItem("count", newVal));
</script>

<template>
  <img alt="Vue logo" src="./assets/logo.png" />
  <h2>子应用1</h2>
  <h2>{{ initCount }}</h2>
  <button type="button" @click="initCount++">count ++</button>
  <button type="button" @click="jumpProject({ postData: initCount })">
    返回首屏
  </button>
  <HelloWorld msg="Hello Vue 3 + TypeScript + Vite" />
</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// src/projects/reactApp/src/App.jsx
import { useState,useEffect } from 'react'
import logo from './logo.svg'
import './App.css'
import { jumpProject } from "@/utils";
const whiteList = ["http://localhost:8080"];
function App() {
  window.addEventListener(
    "message",
    (event) => {
      if (!whiteList.includes(event.origin)) return;
      localStorage.setItem("count", event.data);
    },
    false
  );
  const [count, setCount] = useState(Number(localStorage.getItem("count")))
  useEffect(()=>{
    localStorage.setItem("count", count);
  },[count])
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>Hello Vite + React!</p>
        <p>
          <button type="button" onClick={() => setCount((count) => count + 1)}>
            count is: {count}
          </button>
          <button type="button" onClick={() => jumpProject({postData:count})}>
            返回首屏
          </button>
        </p>
        <p>
          Edit <code>App.jsx</code> and save to test HMR updates.
        </p>
        <p>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
          {' | '}
          <a
            className="App-link"
            href="https://vitejs.dev/guide/features.html"
            target="_blank"
            rel="noopener noreferrer"
          >
            Vite Docs
          </a>
        </p>
      </header>
    </div>
  )
}

export default App
